### ISSUE TITLE
go modules support

### ISSUE THREAD

**Issue by at-wat** [seqsense/aws-iot-device-sdk-go#26]
like below?
```yaml
language: go
matrix:
  include:
  - name: "1.11 modules"
    go: "1.11"
    env: GO111MODULE=on
  - name: "1.11"
    go: "1.11"
  - name: "master modules"
    go: "master"
    env: GO111MODULE=on
  - name: "master"
    go: "master"
```
